#!/bin/bash

# Don't put duplicate lines in the history. See bash(1) for more options 
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000 
HISTFILESIZE=2000 

if [ -e ${HOME}/.bash_history.d ]; then
    HISTFILE="${HOME}/.bash_history.d/$(hostname).history" 
fi
